// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tAyWBPhbw0dVo5ei4saCkPDRy2XJW0Y',
    appId: '1:285671506435:web:9fcbfba54ec2386b314436',
    messagingSenderId: '285671506435',
    projectId: 'familyos-7fd92',
    authDomain: 'familyos-7fd92.firebaseapp.com',
    storageBucket: 'familyos-7fd92.firebasestorage.app',
    measurementId: 'G-BSW4QZM0L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAivJRMpvzKMkzmMETjoWKG-KYIC-1ViE',
    appId: '1:285671506435:android:053a0ef8852d0ef1314436',
    messagingSenderId: '285671506435',
    projectId: 'familyos-7fd92',
    storageBucket: 'familyos-7fd92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh3de2Oh9sUhRDPER1_8I0rrBunIq7WOs',
    appId: '1:285671506435:ios:0e1bbad9775f63e4314436',
    messagingSenderId: '285671506435',
    projectId: 'familyos-7fd92',
    storageBucket: 'familyos-7fd92.firebasestorage.app',
    iosBundleId: 'com.example.familyos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh3de2Oh9sUhRDPER1_8I0rrBunIq7WOs',
    appId: '1:285671506435:ios:0e1bbad9775f63e4314436',
    messagingSenderId: '285671506435',
    projectId: 'familyos-7fd92',
    storageBucket: 'familyos-7fd92.firebasestorage.app',
    iosBundleId: 'com.example.familyos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tAyWBPhbw0dVo5ei4saCkPDRy2XJW0Y',
    appId: '1:285671506435:web:88e616e82145f8f5314436',
    messagingSenderId: '285671506435',
    projectId: 'familyos-7fd92',
    authDomain: 'familyos-7fd92.firebaseapp.com',
    storageBucket: 'familyos-7fd92.firebasestorage.app',
    measurementId: 'G-7BPRLKQST9',
  );
}
